version: "3.3"

services:
  # Web proxy and SSL
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=stream@sfll.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  camapp:
    image: "camapp:latest"
    container_name: camapp
    restart: always
    depends_on:
      - traefik
    ports:
      - "9090:9090"
    volumes:
      - "./cam-app/app/secrets.json:/code/app/secrets.json"  # in case secrets need to change
      - "./cam-app/app/static:/code/app/static"  # field image path (upgrades with cron)
      - "./jobs:/code/jobs" # sqlite db

      # statics
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.camapp.rule=Host(`tcam.sfll.org`)"
      - "traefik.http.routers.camapp.entrypoints=websecure"
      - "traefik.http.routers.camapp.tls.certresolver=myresolver"