version: "3.3"

services:
  camapp:
    image: "camapp:latest"
    container_name: camapp
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - "./cam-app/.env"  # Load environment variables from .env file
    volumes:
      - "./cam-app/app/static:/code/app/static"  # field image path (upgrades with cron)
      - "./jobs:/code/jobs" # sqlite db
      - "./logs:/code/logs" # log files
